import type { TabId } from '@/types/navigation';

import {
  Home,
  Scan,
  Shield,
  MessageSquare,
  Download,
  Link,
  FileSearch,
  Lock,
  Database,
  AlertTriangle,
  Smartphone,
  TrendingUp,
  GraduationCap,
  Brain,
  Camera,
  Phone,
  MessageCircle,
  Newspaper,
  Search,
} from 'lucide-react';

export type NavItem = {
  id: TabId;
  label: string;
  icon: any;
};

export const NAV_ITEMS: Record<'en' | 'hi', NavItem[]> = {
  en: [
    { id: 'home', label: 'Home', icon: Home },
    { id: 'scanner', label: 'AI Scanner', icon: Scan },
    { id: 'threats', label: 'Threat Intel', icon: TrendingUp },
    { id: 'apk', label: 'APK Guardian', icon: Shield },
    { id: 'sms', label: 'SMS Guardian', icon: MessageSquare },
    { id: 'downloads', label: 'Download Scanner', icon: Download },
    { id: 'url', label: 'URL Check', icon: Link },
    { id: 'spam', label: 'Spam AI', icon: MessageSquare },
    { id: 'file', label: 'File Scan', icon: FileSearch },
    { id: 'encryption', label: 'File Encryption', icon: Lock },
    { id: 'breach', label: 'Breach Check', icon: Database },
    { id: 'ransomware', label: 'Ransomware Detect', icon: AlertTriangle },
    { id: 'device', label: 'Device Check', icon: Smartphone },
    { id: 'news', label: 'Latest Threats', icon: TrendingUp },
    { id: 'education', label: 'Learn Safety', icon: GraduationCap },
    { id: 'aboutai', label: 'AI Tech', icon: Brain },
    { id: 'evidence', label: 'Evidence Collector', icon: Camera },
    { id: 'report', label: 'Police Report', icon: Shield },
    { id: 'scamdb', label: 'Scam Database', icon: Database },
    { id: 'aianalyzer', label: 'AI Call Analyzer', icon: Brain },
    { id: 'emergency', label: 'Emergency Contacts', icon: Phone },
    { id: 'simprotection', label: 'SIM Protection', icon: Smartphone },
    { id: 'devicescan', label: 'Device Scanner', icon: Search },
    { id: 'whatsapp', label: 'WhatsApp Safety', icon: MessageCircle },
    { id: 'awareness', label: 'Scam Alerts', icon: Newspaper },
    { id: 'privacy', label: 'Privacy Shield', icon: Lock },
  ],
  hi: [
    { id: 'home', label: 'होम', icon: Home },
    { id: 'scanner', label: 'AI स्कैनर', icon: Scan },
    { id: 'threats', label: 'खतरा इंटेल', icon: TrendingUp },
    { id: 'apk', label: 'APK गार्डियन', icon: Shield },
    { id: 'sms', label: 'SMS गार्डियन', icon: MessageSquare },
    { id: 'downloads', label: 'डाउनलोड स्कैनर', icon: Download },
    { id: 'url', label: 'URL जांच', icon: Link },
    { id: 'spam', label: 'स्पैम AI', icon: MessageSquare },
    { id: 'file', label: 'फ़ाइल स्कैन', icon: FileSearch },
    { id: 'encryption', label: 'फ़ाइल एन्क्रिप्शन', icon: Lock },
    { id: 'breach', label: 'ब्रीच जांच', icon: Database },
    { id: 'ransomware', label: 'रैंसमवेयर पहचान', icon: AlertTriangle },
    { id: 'device', label: 'डिवाइस जांच', icon: Smartphone },
    { id: 'news', label: 'नवीनतम खतरे', icon: TrendingUp },
    { id: 'education', label: 'सुरक्षा सीखें', icon: GraduationCap },
    { id: 'aboutai', label: 'AI तकनीक', icon: Brain },
    { id: 'evidence', label: 'सबूत संग्रह', icon: Camera },
    { id: 'report', label: 'पुलिस रिपोर्ट', icon: Shield },
    { id: 'scamdb', label: 'घोटाला डेटाबेस', icon: Database },
    { id: 'aianalyzer', label: 'AI कॉल विश्लेषक', icon: Brain },
    { id: 'emergency', label: 'आपात संपर्क', icon: Phone },
    { id: 'simprotection', label: 'SIM सुरक्षा', icon: Smartphone },
    { id: 'devicescan', label: 'डिवाइस स्कैनर', icon: Search },
    { id: 'whatsapp', label: 'व्हाट्सएप सुरक्षा', icon: MessageCircle },
    { id: 'awareness', label: 'घोटाला अलर्ट', icon: Newspaper },
    { id: 'privacy', label: 'गोपनीयता शील्ड', icon: Lock },
  ],
};
