export const TAB_IDS = [
  'home',
  'scanner',
  'threats',
  'apk',
  'sms',
  'downloads',
  'url',
  'spam',
  'file',
  'encryption',
  'breach',
  'ransomware',
  'device',
  'news',
  'education',
  'aboutai',
  'evidence',
  'report',
  'scamdb',
  'aianalyzer',
  'emergency',
  'simprotection',
  'devicescan',
  'whatsapp',
  'awareness',
  'privacy',
  'system-guardian',
  'phoneguard',
  'legal-rights',
  'sentinel',
] as const;

export type TabId = (typeof TAB_IDS)[number];
