'use client';
import { useState, useEffect, useMemo } from 'react';
import {
  Globe, Shield, Phone, ExternalLink, Search, MapPin,
  AlertTriangle, ChevronRight, BookOpen, FileText,
  Radio, CheckCircle, Zap, Copy, Navigation
} from 'lucide-react';
import globalSafetyData from '@/data/global-safety.json';

/* ─── Types ─── */
interface Country {
  code: string; name: string; flag: string; region: string;
  cyber_hotline: string; cyber_portal: string;
  police: string; ambulance: string; fire: string;
  cyber_agency: string; report_url: string;
  top_scams: string[]; scam_alert: string; languages: string[];
}

const countries: Country[] = globalSafetyData.countries as Country[];

const LS_COUNTRY = 'qs_shield_country';
const LS_OVERRIDE = 'qs_shield_manual_override';

/* ─── Auto-detect country from browser locale ─── */
function detectBrowserCountry(): string {
  if (typeof navigator === 'undefined') return 'IN';
  const lang = navigator.language || 'en-IN';
  const parts = lang.split('-');
  if (parts.length >= 2) return parts[parts.length - 1].toUpperCase();
  // Fallback mapping for single-part locales
  const localeMap: Record<string, string> = {
    hi: 'IN', en: 'IN', ar: 'SA', zh: 'CN', fr: 'FR',
    de: 'DE', es: 'ES', pt: 'BR', ja: 'JP', ko: 'KR',
    ru: 'RU', it: 'IT', nl: 'NL', tr: 'TR', pl: 'PL',
    sv: 'SE', no: 'NO', id: 'ID', ms: 'MY', th: 'TH',
  };
  return localeMap[parts[0]] || 'IN';
}

/* ─── Format phone for tel: link ─── */
function telLink(num: string) {
  return `tel:${num.replace(/[^0-9+]/g, '')}`;
}

/* ═══════════════════════════════════════════════════════════════════
   COMPONENT
═══════════════════════════════════════════════════════════════════ */
export default function GlobalGuardian({ lang = 'en' }: { lang?: 'en' | 'hi' }) {
  const [selectedCode, setSelectedCode] = useState<string>('IN');
  const [isManual, setIsManual] = useState(false);
  const [search, setSearch] = useState('');
  const [activeTab, setActiveTab] = useState<'passport' | 'shield' | 'threats' | 'report'>('passport');
  const [copied, setCopied] = useState(false);
  const [showPicker, setShowPicker] = useState(false);

  /* ─── Load saved / auto-detect ─── */
  useEffect(() => {
    const saved = localStorage.getItem(LS_COUNTRY);
    const manual = localStorage.getItem(LS_OVERRIDE) === 'true';
    if (saved) { setSelectedCode(saved); setIsManual(manual); }
    else {
      const auto = detectBrowserCountry();
      const match = countries.find(c => c.code === auto);
      setSelectedCode(match ? auto : 'IN');
    }
  }, []);

  const country = useMemo(
    () => countries.find(c => c.code === selectedCode) ?? countries[0],
    [selectedCode]
  );

  const filteredCountries = useMemo(
    () => countries.filter(c =>
      c.name.toLowerCase().includes(search.toLowerCase()) ||
      c.code.toLowerCase().includes(search.toLowerCase()) ||
      c.region.toLowerCase().includes(search.toLowerCase())
    ),
    [search]
  );

  const selectCountry = (code: string, manual: boolean) => {
    setSelectedCode(code);
    setIsManual(manual);
    localStorage.setItem(LS_COUNTRY, code);
    localStorage.setItem(LS_OVERRIDE, String(manual));
    setShowPicker(false);
    setSearch('');
  };

  const autoDetect = () => {
    const auto = detectBrowserCountry();
    const match = countries.find(c => c.code === auto);
    selectCountry(match ? auto : 'IN', false);
  };

  /* ─── Generate pre-filled report ─── */
  const generateReport = () => {
    const cbState = JSON.parse(localStorage.getItem('qs_cb_state') || '{}');
    const callStart = cbState.callStartTime
      ? new Date(cbState.callStartTime).toLocaleString() : 'N/A';
    const duration = cbState.callStartTime
      ? Math.round((Date.now() - cbState.callStartTime) / 60000) + ' minutes' : 'N/A';
    const caller = cbState.callerLabel || 'Unknown';

    return `CYBERCRIME INCIDENT REPORT
Generated by QuantumShield — ${new Date().toLocaleString()}
Reporting to: ${country.cyber_agency}
Portal: ${country.report_url}
Hotline: ${country.cyber_hotline}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INCIDENT DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Incident Type: Suspected Virtual Kidnapping / Isolation Scam
Country: ${country.name} (${country.code})
Date/Time: ${new Date().toLocaleString()}
Call Started: ${callStart}
Duration: ${duration}
Unknown Caller Label: ${caller}

WHAT HAPPENED:
The victim was engaged in an extended WhatsApp call with an unknown
number. During this period, the victim was unreachable by family/
emergency contacts. QuantumShield's Anti-Isolation Protocol (Circuit
Breaker) detected this pattern after 6+ hours.

Common scam type in ${country.name}: ${country.top_scams[0]}

EVIDENCE:
• Circuit Breaker Alert triggered automatically
• Call start timestamp: ${callStart}
• Missed emergency calls logged by QuantumShield

ACTIONS TAKEN:
• Distress signal sent to Safety Circle contacts
• Location shared with family (if GPS was available)
• This report generated for law enforcement

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMPORTANT: File this report at ${country.report_url}
Or call: ${country.cyber_hotline}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;
  };

  const copyReport = () => {
    navigator.clipboard.writeText(generateReport()).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  /* ─── Region colour ─── */
  const regionColor: Record<string, string> = {
    Asia: 'text-orange-400', Americas: 'text-blue-400',
    Europe: 'text-purple-400', Africa: 'text-green-400',
    Oceania: 'text-cyan-400', 'Middle East': 'text-yellow-400',
    'Europe/Asia': 'text-pink-400',
  };

  /* ═══ RENDER ═══ */
  return (
    <div className="max-w-4xl mx-auto p-4 md:p-6 text-white">

      {/* ── Header ── */}
      <div className="relative overflow-hidden rounded-2xl mb-6 border border-blue-500/30 bg-gradient-to-br from-slate-900 via-blue-950/50 to-slate-900 p-6">
        <div className="absolute inset-0 opacity-10"
          style={{ backgroundImage: 'radial-gradient(circle at 20% 50%, #3b82f6 0%, transparent 50%), radial-gradient(circle at 80% 50%, #8b5cf6 0%, transparent 50%)' }} />
        <div className="relative z-10">
          <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
            <span className="text-xs font-mono bg-blue-600/20 border border-blue-500/40 text-blue-400 px-3 py-1 rounded-full tracking-widest">
              GLOBAL GUARDIAN
            </span>
            <button
              onClick={() => setShowPicker(true)}
              className="flex items-center gap-2 bg-white/10 hover:bg-white/20 px-3 py-1.5 rounded-lg text-sm font-semibold transition-all"
            >
              <span className="text-xl">{country.flag}</span>
              <span>{country.name}</span>
              <Globe className="w-3.5 h-3.5 text-blue-400" />
            </button>
          </div>
          <h1 className="text-3xl md:text-4xl font-black tracking-tight mb-1">Global Guardian</h1>
          <p className="text-sm text-gray-400">
            World Cyber Safety Directory · {countries.length} Countries · Offline-First
          </p>
          {!isManual && (
            <p className="text-xs text-blue-400 mt-2 flex items-center gap-1">
              <Navigation className="w-3 h-3" /> Auto-detected: {country.name}
            </p>
          )}
          {isManual && (
            <p className="text-xs text-yellow-400 mt-2 flex items-center gap-1">
              <MapPin className="w-3 h-3" /> Manual override: {country.name}
              <button onClick={autoDetect} className="ml-2 underline text-blue-400 hover:text-blue-300">Auto-detect</button>
            </p>
          )}
        </div>
      </div>

      {/* ── Country Picker Modal ── */}
      {showPicker && (
        <div className="fixed inset-0 bg-black/80 z-50 flex items-end md:items-center justify-center p-4">
          <div className="bg-gray-900 border border-white/10 rounded-2xl w-full max-w-lg max-h-[80vh] flex flex-col">
            <div className="p-4 border-b border-white/10">
              <h3 className="font-bold text-lg mb-3">Select Shield Region</h3>
              <div className="flex items-center gap-2 bg-black/40 border border-white/10 rounded-xl px-3">
                <Search className="w-4 h-4 text-gray-500 shrink-0" />
                <input
                  autoFocus
                  value={search}
                  onChange={e => setSearch(e.target.value)}
                  placeholder="Search country..."
                  className="flex-1 bg-transparent py-2.5 text-sm text-white placeholder-gray-500 outline-none"
                />
              </div>
              <button onClick={autoDetect}
                className="mt-2 w-full text-xs text-blue-400 hover:text-blue-300 flex items-center justify-center gap-1 py-1">
                <Navigation className="w-3 h-3" /> Auto-detect from browser
              </button>
            </div>
            <div className="overflow-y-auto flex-1 p-2">
              {filteredCountries.map(c => (
                <button
                  key={c.code}
                  onClick={() => selectCountry(c.code, true)}
                  className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-left hover:bg-white/10 transition-all ${
                    c.code === selectedCode ? 'bg-blue-500/20 border border-blue-500/40' : ''
                  }`}
                >
                  <span className="text-2xl">{c.flag}</span>
                  <div className="flex-1 min-w-0">
                    <div className="font-semibold text-sm">{c.name}</div>
                    <div className={`text-xs ${regionColor[c.region] || 'text-gray-500'}`}>{c.region}</div>
                  </div>
                  <span className="text-xs text-gray-500 font-mono">{c.code}</span>
                  {c.code === selectedCode && <CheckCircle className="w-4 h-4 text-blue-400" />}
                </button>
              ))}
              {filteredCountries.length === 0 && (
                <p className="text-gray-500 text-sm text-center py-8">No countries found</p>
              )}
            </div>
            <div className="p-4 border-t border-white/10">
              <button onClick={() => { setShowPicker(false); setSearch(''); }}
                className="w-full bg-gray-700 hover:bg-gray-600 text-white font-semibold py-2.5 rounded-xl">
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Tabs ── */}
      <div className="flex gap-1 bg-white/5 rounded-xl p-1 mb-6 overflow-x-auto">
        {([
          { id: 'passport', label: 'Safety Passport' },
          { id: 'shield',   label: 'Country Shield' },
          { id: 'threats',  label: 'Geo Threats' },
          { id: 'report',   label: 'Report Now' },
        ] as const).map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex-1 min-w-max text-sm py-2 px-3 rounded-lg font-semibold transition-all ${
              activeTab === tab.id
                ? 'bg-blue-600 text-white shadow'
                : 'text-gray-400 hover:text-white hover:bg-white/5'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* ══════════════════════════════════════════════
          TAB: SAFETY PASSPORT
      ══════════════════════════════════════════════ */}
      {activeTab === 'passport' && (
        <div className="space-y-4">
          {/* Passport card */}
          <div className="relative overflow-hidden rounded-2xl border border-blue-500/40 bg-gradient-to-br from-blue-950 via-slate-900 to-indigo-950 p-6">
            <div className="absolute top-0 right-0 w-32 h-32 opacity-5"
              style={{ backgroundImage: 'radial-gradient(circle, #60a5fa 0%, transparent 70%)' }} />
            <div className="flex items-start justify-between mb-5">
              <div>
                <div className="text-xs font-mono text-blue-400 tracking-widest mb-1">QUANTUM SHIELD</div>
                <div className="text-xs text-gray-500">DIGITAL SAFETY PASSPORT</div>
              </div>
              <div className="text-5xl">{country.flag}</div>
            </div>

            <div className="grid grid-cols-2 gap-4 mb-5">
              <div>
                <div className="text-xs text-gray-500 mb-1">SHIELD REGION</div>
                <div className="font-black text-lg">{country.name}</div>
                <div className={`text-xs ${regionColor[country.region] || 'text-gray-400'}`}>{country.region}</div>
              </div>
              <div>
                <div className="text-xs text-gray-500 mb-1">CYBER AGENCY</div>
                <div className="text-sm font-semibold leading-snug">{country.cyber_agency}</div>
              </div>
              <div>
                <div className="text-xs text-gray-500 mb-1">CYBER HOTLINE</div>
                <a href={telLink(country.cyber_hotline)}
                  className="font-black text-xl text-green-400 hover:text-green-300">
                  {country.cyber_hotline}
                </a>
              </div>
              <div>
                <div className="text-xs text-gray-500 mb-1">DETECTION MODE</div>
                <div className={`text-sm font-semibold flex items-center gap-1 ${isManual ? 'text-yellow-400' : 'text-blue-400'}`}>
                  {isManual ? <><MapPin className="w-3 h-3" /> Manual</> : <><Navigation className="w-3 h-3" /> Auto</>}
                </div>
              </div>
            </div>

            <div className="border-t border-white/10 pt-4">
              <div className="text-xs text-gray-500 mb-2">PROTOCOL STATUS</div>
              <div className="flex gap-2 flex-wrap">
                {['Circuit Breaker Active', 'Offline Directory', 'Global Coverage'].map(s => (
                  <span key={s} className="text-xs bg-green-500/10 border border-green-500/30 text-green-400 px-2 py-1 rounded-full flex items-center gap-1">
                    <CheckCircle className="w-2.5 h-2.5" /> {s}
                  </span>
                ))}
              </div>
            </div>
          </div>

          {/* Quick-dial strip */}
          <div className="grid grid-cols-3 gap-3">
            {[
              { label: 'Cyber Hotline', num: country.cyber_hotline, color: 'bg-red-600 hover:bg-red-500' },
              { label: 'Police', num: country.police, color: 'bg-blue-600 hover:bg-blue-500' },
              { label: 'Ambulance', num: country.ambulance, color: 'bg-green-600 hover:bg-green-500' },
            ].map(btn => (
              <a key={btn.label} href={telLink(btn.num)}
                className={`${btn.color} rounded-xl py-3 flex flex-col items-center gap-1 transition-all`}>
                <Phone className="w-5 h-5 text-white" />
                <span className="text-white text-xs font-semibold">{btn.label}</span>
                <span className="text-white font-black text-sm">{btn.num}</span>
              </a>
            ))}
          </div>

          {/* Change region */}
          <button
            onClick={() => setShowPicker(true)}
            className="w-full bg-white/5 border border-dashed border-white/20 hover:border-white/40 hover:bg-white/10 text-gray-400 hover:text-white py-3 rounded-xl flex items-center justify-center gap-2 transition-all text-sm font-semibold"
          >
            <Globe className="w-4 h-4" /> Change Shield Region ({countries.length} countries available)
          </button>
        </div>
      )}

      {/* ══════════════════════════════════════════════
          TAB: COUNTRY SHIELD
      ══════════════════════════════════════════════ */}
      {activeTab === 'shield' && (
        <div className="space-y-4">
          <div className="flex items-center gap-3 mb-2">
            <span className="text-3xl">{country.flag}</span>
            <div>
              <h2 className="text-xl font-black">{country.name} Cyber Shield</h2>
              <p className={`text-sm ${regionColor[country.region] || 'text-gray-400'}`}>{country.region}</p>
            </div>
          </div>

          {/* Emergency numbers */}
          <div className="grid grid-cols-2 gap-3">
            {[
              { label: 'Cybercrime Hotline', num: country.cyber_hotline, icon: Shield, color: 'border-red-500/40 bg-red-500/10' },
              { label: 'Police', num: country.police, icon: Phone, color: 'border-blue-500/40 bg-blue-500/10' },
              { label: 'Ambulance', num: country.ambulance, icon: Zap, color: 'border-green-500/40 bg-green-500/10' },
              { label: 'Fire', num: country.fire, icon: AlertTriangle, color: 'border-orange-500/40 bg-orange-500/10' },
            ].map(item => {
              const Icon = item.icon;
              return (
                <a key={item.label} href={telLink(item.num)}
                  className={`border rounded-xl p-4 flex items-center gap-3 transition-all hover:opacity-80 ${item.color}`}>
                  <Icon className="w-5 h-5 text-white shrink-0" />
                  <div>
                    <div className="text-xs text-gray-400">{item.label}</div>
                    <div className="font-black text-lg text-white">{item.num}</div>
                  </div>
                </a>
              );
            })}
          </div>

          {/* Cyber agency + portal */}
          <div className="bg-white/5 border border-white/10 rounded-xl p-5 space-y-3">
            <div>
              <div className="text-xs text-gray-500 mb-1">CYBER AUTHORITY</div>
              <div className="font-semibold">{country.cyber_agency}</div>
            </div>
            <a href={country.cyber_portal} target="_blank" rel="noopener noreferrer"
              className="flex items-center gap-2 text-blue-400 hover:text-blue-300 text-sm font-semibold transition-all">
              <ExternalLink className="w-4 h-4" /> {country.cyber_portal}
            </a>
            <a href={country.report_url} target="_blank" rel="noopener noreferrer"
              className="w-full block text-center bg-blue-600 hover:bg-blue-500 text-white font-bold py-3 rounded-xl transition-all">
              File Official Report →
            </a>
          </div>

          {/* Top scams in this country */}
          <div className="bg-white/5 border border-white/10 rounded-xl p-5">
            <h3 className="font-bold text-sm mb-3 flex items-center gap-2 text-orange-400">
              <AlertTriangle className="w-4 h-4" /> Top Scams in {country.name}
            </h3>
            <div className="space-y-2">
              {country.top_scams.map((scam, i) => (
                <div key={i} className="flex items-center gap-2 text-sm">
                  <span className="w-5 h-5 rounded-full bg-orange-500/20 border border-orange-500/40 text-orange-400 text-xs flex items-center justify-center font-bold shrink-0">
                    {i + 1}
                  </span>
                  <span className="text-gray-300">{scam}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Compare other countries */}
          <div className="bg-white/5 border border-white/10 rounded-xl p-4">
            <h3 className="font-bold text-sm mb-3 text-gray-400">Other Countries</h3>
            <div className="grid grid-cols-4 md:grid-cols-6 gap-2">
              {countries.filter(c => c.code !== selectedCode).slice(0, 12).map(c => (
                <button key={c.code} onClick={() => selectCountry(c.code, true)}
                  className="flex flex-col items-center gap-1 p-2 rounded-lg hover:bg-white/10 transition-all text-xs text-gray-400 hover:text-white">
                  <span className="text-2xl">{c.flag}</span>
                  <span className="truncate w-full text-center">{c.code}</span>
                </button>
              ))}
            </div>
            <button onClick={() => setShowPicker(true)}
              className="w-full mt-2 text-xs text-blue-400 hover:text-blue-300 py-1">
              View all {countries.length} countries →
            </button>
          </div>
        </div>
      )}

      {/* ══════════════════════════════════════════════
          TAB: GEO THREATS
      ══════════════════════════════════════════════ */}
      {activeTab === 'threats' && (
        <div className="space-y-4">
          {/* Country alert banner */}
          <div className="bg-amber-500/10 border border-amber-500/40 rounded-xl p-5">
            <div className="flex items-start gap-3">
              <span className="text-3xl">{country.flag}</span>
              <div>
                <div className="font-bold text-amber-300 mb-1 flex items-center gap-2">
                  <Radio className="w-4 h-4 animate-pulse" />
                  Live Threat Alert — {country.name}
                </div>
                <p className="text-sm text-gray-300 leading-relaxed">{country.scam_alert}</p>
              </div>
            </div>
          </div>

          {/* Scam types detail */}
          <div className="space-y-3">
            {country.top_scams.map((scam, i) => (
              <div key={i} className="bg-white/5 border border-white/10 rounded-xl p-4 flex items-start gap-3">
                <div className={`w-8 h-8 rounded-full flex items-center justify-center font-black text-sm shrink-0 ${
                  i === 0 ? 'bg-red-600/30 text-red-400 border border-red-500/40' :
                  i === 1 ? 'bg-orange-600/30 text-orange-400 border border-orange-500/40' :
                  'bg-yellow-600/30 text-yellow-400 border border-yellow-500/40'
                }`}>#{i + 1}</div>
                <div className="flex-1">
                  <div className="font-semibold text-sm mb-1">{scam}</div>
                  <div className="text-xs text-gray-500">
                    Report to: {country.cyber_hotline} · {country.cyber_agency}
                  </div>
                </div>
                <a href={country.report_url} target="_blank" rel="noopener noreferrer"
                  className="text-blue-400 hover:text-blue-300">
                  <ExternalLink className="w-4 h-4" />
                </a>
              </div>
            ))}
          </div>

          {/* Jurisdiction mismatch warning */}
          <div className="bg-purple-500/10 border border-purple-500/30 rounded-xl p-5">
            <div className="flex items-center gap-2 text-purple-400 font-bold text-sm mb-2">
              <Shield className="w-4 h-4" /> Jurisdiction Mismatch Defence
            </div>
            <p className="text-xs text-gray-400 leading-relaxed">
              If a caller claims to be from a foreign government agency (e.g., "Interpol", "US FBI",
              "Dubai Police") but you are currently in <strong className="text-white">{country.name}</strong>,
              this is a <strong className="text-red-400">scam red flag</strong>. Foreign agencies never
              contact individuals directly. Your real authority is:
            </p>
            <div className="mt-3 bg-black/30 rounded-lg p-3 text-sm">
              <div className="font-semibold text-white">{country.cyber_agency}</div>
              <a href={telLink(country.cyber_hotline)} className="text-green-400 font-black text-lg block mt-1">
                {country.cyber_hotline}
              </a>
            </div>
          </div>

          {/* Global comparison */}
          <div className="bg-white/5 border border-white/10 rounded-xl p-5">
            <h3 className="font-bold text-sm mb-3 flex items-center gap-2">
              <Globe className="w-4 h-4 text-blue-400" /> High-Risk Countries — Cyber Fraud 2025–26
            </h3>
            {[
              { code: 'IN', name: 'India', flag: '🇮🇳', risk: 'CRITICAL', tag: '₹1,935Cr Digital Arrests' },
              { code: 'US', name: 'United States', flag: '🇺🇸', risk: 'HIGH', tag: '$10.3B IC3 reported losses' },
              { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', risk: 'HIGH', tag: '£2.35B APP fraud' },
              { code: 'BR', name: 'Brazil', flag: '🇧🇷', risk: 'HIGH', tag: 'PIX fraud 1000+/day' },
              { code: 'SG', name: 'Singapore', flag: '🇸🇬', risk: 'HIGH', tag: 'SGD $1.1B lost 2024' },
              { code: 'MY', name: 'Malaysia', flag: '🇲🇾', risk: 'MEDIUM', tag: 'Macau Scam epidemic' },
            ].map(r => (
              <div key={r.code} className="flex items-center gap-3 py-2 border-b border-white/5 last:border-0 cursor-pointer hover:bg-white/5 rounded-lg px-1"
                onClick={() => selectCountry(r.code, true)}>
                <span className="text-xl">{r.flag}</span>
                <div className="flex-1">
                  <div className="text-sm font-semibold">{r.name}</div>
                  <div className="text-xs text-gray-500">{r.tag}</div>
                </div>
                <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${
                  r.risk === 'CRITICAL' ? 'bg-red-500/20 text-red-400' :
                  r.risk === 'HIGH' ? 'bg-orange-500/20 text-orange-400' :
                  'bg-yellow-500/20 text-yellow-400'
                }`}>{r.risk}</span>
                <ChevronRight className="w-4 h-4 text-gray-600" />
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ══════════════════════════════════════════════
          TAB: REPORT NOW
      ══════════════════════════════════════════════ */}
      {activeTab === 'report' && (
        <div className="space-y-4">
          <div>
            <h2 className="text-xl font-bold mb-1">One-Click Incident Report</h2>
            <p className="text-sm text-gray-400">
              Pre-filled with your Circuit Breaker data. Copy and paste into the official portal.
            </p>
          </div>

          {/* Quick actions */}
          <div className="grid grid-cols-2 gap-3">
            <a href={telLink(country.cyber_hotline)}
              className="bg-red-600 hover:bg-red-500 text-white font-bold py-4 rounded-xl flex flex-col items-center gap-1 transition-all">
              <Phone className="w-5 h-5" />
              <span className="text-xs">Call Cyber Hotline</span>
              <span className="font-black">{country.cyber_hotline}</span>
            </a>
            <a href={country.report_url} target="_blank" rel="noopener noreferrer"
              className="bg-blue-600 hover:bg-blue-500 text-white font-bold py-4 rounded-xl flex flex-col items-center gap-1 transition-all">
              <ExternalLink className="w-5 h-5" />
              <span className="text-xs">File Online Report</span>
              <span className="text-xs font-bold truncate w-full text-center px-2">
                {country.cyber_agency.split('/')[0].trim()}
              </span>
            </a>
          </div>

          {/* Pre-filled report */}
          <div className="bg-white/5 border border-white/10 rounded-xl p-5">
            <div className="flex items-center justify-between mb-3">
              <h3 className="font-bold text-sm flex items-center gap-2">
                <FileText className="w-4 h-4 text-yellow-400" /> Pre-Filled Incident Report
              </h3>
              <button onClick={copyReport}
                className={`flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg font-semibold transition-all ${
                  copied
                    ? 'bg-green-600/20 text-green-400 border border-green-500/40'
                    : 'bg-white/10 hover:bg-white/20 text-gray-300'
                }`}>
                {copied ? <CheckCircle className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied!' : 'Copy Report'}
              </button>
            </div>
            <pre className="text-xs text-gray-400 leading-relaxed overflow-x-auto whitespace-pre-wrap font-mono bg-black/30 rounded-lg p-4 max-h-72 overflow-y-auto">
              {generateReport()}
            </pre>
          </div>

          {/* What to do next */}
          <div className="bg-blue-500/5 border border-blue-500/20 rounded-xl p-5 space-y-3">
            <h3 className="font-bold text-sm text-blue-400 flex items-center gap-2">
              <BookOpen className="w-4 h-4" /> What To Do Next — {country.name}
            </h3>
            {[
              `Call ${country.cyber_hotline} immediately — report within 24h for maximum fund recovery chance`,
              `File online at ${country.report_url} — attach this report`,
              `Inform your bank immediately — request transaction freeze/reversal`,
              `Report to ${country.cyber_agency} for investigation`,
              `Contact Circuit Breaker Safety Circle contacts to confirm your safety`,
            ].map((step, i) => (
              <div key={i} className="flex items-start gap-2 text-xs text-gray-400">
                <span className="w-5 h-5 rounded-full bg-blue-500/20 text-blue-400 text-xs flex items-center justify-center font-bold shrink-0 mt-0.5">
                  {i + 1}
                </span>
                <span>{step}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
